# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Reverb
tagline:
url:              http://reverbcollective.com
paginate:         1
baseurl:          /
author:
  name:           Chris Hayen
  url:            https://twitter.com/tenhaus
  email:          chayen@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tenhaus/reverb
